apiVersion: v1
kind: Service
metadata:
{{- if .Values.serviceUpload.name }}
  name: {{ .Values.serviceUpload.name }}
{{- else }}
  name: {{ template "fullname" . }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
{{- if .Values.serviceUpload.annotations }}
  annotations:
{{ toYaml .Values.serviceUpload.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.serviceUpload.type }}
  ports:
  - port: {{ .Values.serviceUpload.externalPort }}
    targetPort: {{ .Values.serviceUpload.internalPort }}
    protocol: TCP
    name: http
  selector:
    app: {{ template "fullname" . }}
